Add TS types (Fixes #39)
nearform/fastify-auth0-verify pull request #56
Opened 2021-01-01 23:05 UTC by NotWoods

Adds TypeScript types that automatically attach new methods to the fastify instance and request.

2021-01-01 23:15 UTC, mcollina requested changes
Good work!

2021-01-01 23:15 UTC, mcollina commented on test-d.ts
> +})
Could you convert this to a test built with `tsd` and run with `npm test`?

2021-01-02 10:16 UTC, mcollina approved these changes
lgtm

2021-01-02 10:17 UTC, simoneb approved these changes

2021-01-05 16:59 UTC, merged